name: Build AI Docker Images

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'branch (e.g., release)'
        required: true
        default: 'dev'
      version: 
        description: 'image version (e.g., 1.0.0)'
        required: true
        default: 'latest'  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: innet8/ttpos-menu # ghcr.io/your-username/your-repo

jobs:
  # TRABAJO 1: Compilar el binario del Backend
  build-backend:
    name: Build AI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para subir a GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ttpos-menu
          repository: innet8/ttpos-menu # 目标仓库的 owner 和名称
          token: ${{ secrets.OTHER_REPO_TOKEN }} # 使用存储在 secrets 中的 token
          ref: ${{ github.event.inputs.branch }} # 可选：指定要检出的分支或 tag，默认为 default branch

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AI image
        uses: docker/build-push-action@v5
        with:
          context: ./ttpos-menu
          file: ./ttpos-menu/docker/Dockerfile.ai # Usa el Dockerfile de producción
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ai:${{ github.event.inputs.version }}       
 