name: Build Server Docker Images

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: 'branch (e.g., release)'
        required: true
        default: 'dev'
      version: 
        description: 'image version (e.g., 1.0.0)'
        required: true
        default: 'dev'  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: innet8/ttpos-menu # ghcr.io/your-username/your-repo

jobs:
  # TRABAJO 1: Compilar el binario del Backend
  build-backend:
    name: Build server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para subir a GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ttpos-menu
          repository: innet8/ttpos-menu # 目标仓库的 owner 和名称
          token: ${{ secrets.OTHER_REPO_TOKEN }} # 使用存储在 secrets 中的 token
          ref: ${{ github.event.inputs.branch }} # 可选：指定要检出的分支或 tag，默认为 default branch

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build static Go binary
        run: |
          cd ttpos-menu/server
          go mod tidy
          CGO_ENABLED=1 GOOS=linux go build -v -o ../app-server main.go

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./ttpos-menu
          file: ./ttpos-menu/docker/Dockerfile.backend # Usa el Dockerfile de producción
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ github.event.inputs.version }} 

     
