name: Build Server Docker Images

on:
  push:
    tags: 
      - 'v*'
  workflow_dispatch:
    inputs:
      branch: 
        description: 'branch (e.g., release)'
        required: true
        default: 'dev'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # ghcr.io/your-username/your-repo

jobs:
  # TRABAJO 1: Compilar el binario del Backend
  build-backend:
    name: Build server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para subir a GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build static Go binary
        run: |
          cd server
          go mod tidy
          CGO_ENABLED=1 GOOS=linux go build -v -o ../app-server main.go

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.backend # Usa el Dockerfile de producción
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest

     
